---
# ----------------------------------------------------
# RUMAH config file
# ----------------------------------------------------

# Logging level 
# CRITICAL = 50, ERROR = 40, WARNING = 30, INFO = 20, DEBUG = 10, NOTSET = 0
logging_level: 10

# Delay between 2 BLE discoveries (in seconds)
delay: 7

# Pushbullet configuration
pushbullet:
    api: HcP0dywlqiu0dp1NrH6mI3IWAUOB3ZJt

# Home location
location: 43 rue de Menilmontant, Paris

# Checks the presence of the folowwing devices
devices:
    Kad: 
        bdaddr: 80:71:7A:A9:17:27
        notify: True
    Sam: 
        bdaddr: 18:9E:FC:26:03:55
        notify: False

# Bluetooth search timeout (in seconds)
timeout: 3
